/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface InputEvent {
  eventType: string
  payload?: string
  x?: number
  y?: number
}

export declare function startRootListener(callback: (err: Error | null, arg: InputEvent) => any): void
